### ISSUE TITLE
Static Legend follow up

### ISSUE THREAD

**Issue by daviddkkim** [influxdata/ui#1025]
### Target Customer / Background data / Context / Market Size
 - This epic is meant to include missing capabilities from the MVP to make this available to the general cloud user.

### Goals
 - Expand existing static legend capability, thereby increasing the ability to observe, share and collaborate within our platform.
 

### Acceptance Crit

- [ ] as a user, hovering over a line will highlight the corresponding static legend~
- [ ] as a user, i can click on a line to keep it highlighted~
- [ ] as a user, i can cmd+click to highlight multiple lines
- [ ] as a user, I can custom sort the legends 
- [ ] as a user, I can customize what to render on the legends (instead of the default all #group)

### Release Plan
 - TBD

### Team
 - Anchor / Dev Champion: @TCL735 
 - Product Manager: @russorat 
 - Design: @mnorriswalker @daviddkkim 

### alternatives considered
 - An alternative would be for someone to be invited to an org and linked to the cell or dashboard for the incident.

### Technical Background
Users can interact with and customize the legends.

### Design Notes

https://www.figma.com/file/6pwGOv5jyMT2rpU8ugZNM1/Static-Legend?node-id=0%3A1
