### ISSUE TITLE
Implement static legends for Graph (overlaid, stacked) and Band Plot

### ISSUE THREAD

**Issue by desa** [influxdata/ui#14]
### Target Customer / Background data / Context / Market Size
 - Target customer is the developer that want to share a static image of a graph with other people. Currently, the user would have to first hover over the graph so that the legend appears, then take a screenshot. Otherwise, they are stuck describing what the lines in the graph are manually or with a second screenshot.
 - This has frustrated our internal teams during incident management and has been requested
 - Target customer is also someone who wants to share charts on a wallboard which is a non-interactive session

### Goals
 - This only applies to Graph and Band plots for now.
 - The legend should be displayed to the bottom of the cell
 - Allow a configuration option to turn on and off the legend display.
 - Allow a configuration option, which can display the most recent time value for each data series in the legend.
-  Static legend height has a configuration option (model on data explorer resize ui)
 
### Acceptance Crit
- [ ] as a user, when i configure a graph or band graph in the UI, then I have the option to always display a legend on the bottom of the cell.
- [ ] as a user, when i enable the legend on a cell, no changes to hover tooltip display when hovering over different parts of the graph
- [ ] ~as a user, hovering over a line will highlight the corresponding static legend~
- [ ] ~as a user, i can click on a line to keep it highlighted~
- [ ] ~as a user, i can cmd+click to highlight multiple lines~
- [ ] as a user, I can choose to configure whether recent time values will be displayed in the legend
- [ ] as a user, I can choose the height of the static legend in a configuration option
- [ ] as a product owner, i would like to see the number of times a user enables static legends

### Release Plan
 - TBD

### Team
 - Anchor / Dev Champion: @TCL735 
 - Product Manager: @russorat 
 - Design: @mnorriswalker @daviddkkim 

### alternatives considered
 - An alternative would be for someone to be invited to an org and linked to the cell or dashboard for the incident.

### Technical Background
Inspired by the success of the graph bitmap hackathon project, we're going to make exporting a bitmap / screenshot of the graph a first class feature.

Currently all this functionality lives on the frontend as an aspect of [the Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API). 

Branch with image export - https://github.com/influxdata/giraffe/tree/export_images

Server-side rendering of the visualization would be preferred over front-end rendering only. This would unblock future hopes around notification endpoints being able to grab visualizations

### Design Notes

https://www.figma.com/file/6pwGOv5jyMT2rpU8ugZNM1/Static-Legend?node-id=429%3A0

**Comment by philjb** [comment]
I'd love to have this.

**Comment by mnorriswalker** [comment]
I have some design for this. Could we actually solve this problem with export as an image, so it's even better formatted for sharing? https://github.com/influxdata/giraffe/tree/export_images

Other feedback on acceptance criteria:

`as a developer, when i enable the legend to be displayed on the cell, then i have the option of choosing if it is displayed to the right of the cell or the bottom.`

Too much optionality. I think we should just design one way: bottom. It's going to be better for mobile responsiveness. It's just one on/off and less configuring.

`as a developer, when i enable the legend on a cell, it has no impact to the hover legend behavior`

No, the legend should either be static or on-hover. Otherwise, we're just duplicating the content and that's confusing/crowded/overwhelming. I have an interaction in mind when you hover over the graph line then the line item in the legend is highlighted.

**Comment by russorat** [comment]
re: hover legend
i just want to make sure users can still see the value when they hover. i will update.

re: position
sounds good

**Comment by mnorriswalker** [comment]
Possible input/interest from @derektamsen and @ssoroka 
https://influxdata.slack.com/archives/C02GAR82Q/p1614101619361300

**Comment by russorat** [comment]
re: Could we actually solve this problem with export as an image, so it's even better formatted for sharing?
@mnorriswalker i think that should be done regardless of this issue (maybe in conjunction). I'm thinking static legends would still be needed when we save as an image, but i could be wrong.

**Comment by schmorgs** [comment]
My use case is to have the charts on a wallboard which is a non-interactive session

In this situation, multiple people could be looking at the screen at various times and requiring someone to remotely connect to the wallboard and hover over the chart would be unworkable

The legend should be optional, as in current Chronograf, so that users who want to maximise screen space can choose to display or not

**Comment by mnorriswalker** [comment]
@schmorgs thanks for chiming in--great point. Added it to the description of the issue and acceptance criteria.

@russorat - let's go for both (1) being able to turn on a legend so that it's visible on the bottom and (2) being able to export a bitmap. The bitmap export code is already partially developed due to @hoorayimhelping's hackathon project. (1) and (2) covers both use cases of a wallboard and sharing a screenshot via Slack or other socials. I've added a link to the design. I don't believe there are any design blockers on this. Can we move this into the backlog for either UI Team for the 45/90 roadmap outlook? :Excited:

**Comment by russorat** [comment]
@mnorriswalker could you add what the design looks like for displaying the values of the graph? I'm thinking we will need the values in the legend itself. if you aren't hovering on the graph, the legend shows the most recent point for each series. if you are hovering, it shows the value at the hover.

**Comment by mnorriswalker** [comment]
@russorat - agreed about showing values in the legend. will add to the design.

**Comment by barbaranelson** [comment]
Can we move dynamic legends into its own epic? I agree that it would be a cool feature, but I don't think we should hold static legends up to add dynamic legends.

**Comment by russorat** [comment]
@barbaranelson we met as a team today with the engineers and decided as a group that the effort to add values to the static legend was minimal and that it helps with @schmorgs 's use case about displaying this information on a wallboard.

**Comment by daviddkkim** [comment]
In the interest of slimming down the epic for faster delivery,
I moved everything that adds "interactivity" to the static legends to a separate epic : https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/ui/1025

The features that were moved were :
- Interacting with legend and graph by clicking a legend item 
- Interacting with legend and graph by hovering over a legend item
- Sorting legend by custom field 

@TCL735
@russorat 
Please let me know If this is not okay or you would like to see a specific feature definitely included in the MVP. You guys are the leads for this feature!

**Comment by mnorriswalker** [comment]
Love the progress on this. Do we need measurement/analytics Issue and also a Docs issue @russorat @daviddkkim @kelseiv ?

**Comment by russorat** [comment]
@mnorriswalker good catch. i added. Is that good enough for now to track feature adoption?
as a product owner, i would like to see the number of times a user enables static legends

**Comment by mnorriswalker** [comment]
@russorat for measurement, I'm think `enable static legends`, `disable static legends` and `click-to-action share static legends` could be all that's needed.

Docs?

**Comment by daviddkkim** [comment]
@mnorriswalker 
If `click-to-action share static` is for sharing graph w the button, It got moved [out](https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/influxdb/21153). So we might only need `enable static legends` and `disable static legends`
