### ISSUE TITLE
Notebooks: Enable Full Cycle for Tasks

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#3296]
We would like to enable the full cycle for Tasks in Notebooks so that users may have an end to end task experience that begins in a notebook and continues with editing and exploration.

To accomplish this goal, we some items must be completed:

- [x] The ability to specify a task in cron format (#3259 & #2903)
- [x]  Start / create authoring for tasks in Query Builder (#3297)
- [ ] For tasks not created in a Notebook, a new Notebook should be opened with a Flux panel and a schedule panel (#3298)
- [ ] For tasks created in a Notebook, open in the original Notebook (#3299)
- [x] Button to reexport a task (need design) (#3300)
- [ ] Add list of exported tasks to the storage side for use later (#3301)
