### ISSUE TITLE
Notebook (alerts): usability challanges.

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#4079]
When using notebooks, I want to be able to create Alerts which are functional and meaningful. Here is a (non-exhaustive) list of currently known challenges.

## Usability checks
- [ ] OVERALL GOAL:
     * If I generate an alert, and export it to a task --> I want that task to be valid (when running from the Tasks page), and to run according to my inputs set in notebooks.
     * this requires multiple upstream parts (listed below) to be correct.
- [ ] Dataset usage:
     * If I build a dataset using the query builder, and then create an alert based on the resultant dataset --> this Alert should be valid (in terms of the dataset).
     * example bug: DLW TODO
- [ ] Endpoint usage:
     * If I generate an alert using a given endpoint --> I want to know that this Alert is properly triggering the endpoint.
     * example bug: https://github.com/influxdata/ui/issues/3880
- [ ] Time window:
     * If I generate an alert, using a certain time range (lookback window), I want to know that it will work as intended (across this time window).
     * Caveat: thus far, we have not seen this issues with how notebooks does alerts. But if we move closer to the conceptual model of the Alerts section of the app --> we'll run into that problem.
          * example bug (in non-notebooks alerts): https://github.com/influxdata/ui/issues/3803
          * example bug (in non-notebooks alerts): https://github.com/influxdata/ui/issues/3781
- [ ] Suggestions in UI form inputs.
     * I want useful suggestions to know how to fill in the UI form elements.
     * example bug: https://github.com/influxdata/ui/issues/3946
     * example bug: https://github.com/influxdata/ui/issues/3931
- [ ] UI form inputs are being consumed.
     * If I enter information into a UI form, I want to know this information is correctly inserted into the output flux query.
     * example bug: https://github.com/influxdata/ui/issues/3919
- [ ] UI form inputs are being validated:
     * If I enter bad/wrong information into a UI form, I want to be told about it (and not allowed to export the invalid alert query).
     * example bug: https://github.com/influxdata/ui/issues/4022
- [ ] Per each alerting event --> get  1 alert notification.
     * If I ask for an alert to occur under a given condition (per time window), then I should get only 1 alert notification (per time window).
     * https://github.com/influxdata/ui/issues/4034
     * https://github.com/influxdata/ui/issues/3707
- [ ] Trusting in the auto-generated flux.
     * Even if we have all of the above steps, can I trust that the flux alert query built for me (and exported) is valid?
     * many examples:
          * https://github.com/influxdata/ui/issues/3706
          * https://github.com/influxdata/ui/issues/3742
          * https://github.com/influxdata/ui/issues/3764
          * https://github.com/influxdata/ui/issues/3788
          * https://github.com/influxdata/ui/issues/3830
          * https://github.com/influxdata/ui/issues/3846
          * https://github.com/influxdata/ui/issues/3847
          * https://github.com/influxdata/ui/issues/3945
          * https://github.com/influxdata/ui/issues/4021
- [ ] Examining my alert tasks.
     * After I export my alert to tasks, I want to be able to view this tasks. (+ run and edit them.)
     * example bug: https://github.com/influxdata/ui/issues/3780
- [ ] Examining my alert notifications. (a.k.a. notification events.)
     * After I created my alert task, it should run --> triggering many notifications. I want to be able to examine these notifications.
     * I also do not want to get confused between what notifications occur from which parts of the app (e.g. the Alerts section non-notebooks alerts, and the notebook alerts).
     * example bug: https://github.com/influxdata/ui/issues/3710
     * https://github.com/influxdata/ui/issues/3708
