### ISSUE TITLE
LSP UI Improvements

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#4154]
## SPIKE Description

<p></p>

The query experience project is leaning heavy towards a flux editor focused user interface.  As such, it is expected that users will be writing flux manually (with some UI based injection help).  Because of this LSP may be a very important aspect of the solution.

<p></p>

It has been communicated that the current way that the cloud2 interface is utilizing LSP is not as optimal as it could be, which is causing some of the functionality that can be used in other Influx interfaces that utilize it to not be as valuable within the cloud2 UI.  

<p></p>

This spike is for seeing what changes can be made to use all of the features of the  LSP.

<p></p>

The results of this spike will then be evaluated to determine what should be included in the new Query experience being looked at by the Query Experience committee.

<p></p>

## Spike Deliverables

<p></p>

- ~~Proof-of-concept/Prototype of Query Editor with maximum LSP usage~~

- Simple document outlining learnings from the process and how difficult it may be for implementation into an existing or new Query builder

<p></p>

<p></p>

**Comment by garylfowler** [comment]
Link to feature: https://influxdata.productboard.com/feature-board/planning/features/12552818

**Comment by wiedld** [comment]
Had an initial conversation with the LSP team. There is some question as to how the UI is interacting with the LSP communication stream, as well as monaco editor versioning. Will likely require a bit of UI research (e.g. if/why interrupting the stream) and code changes (e.g. allow the pass-through to monaco).

**Comment by wiedld** [comment]
Spike in progress. Implementation steps:
- [ ] Refactor that part of the codebase, such that it's more approachable for UI developers.
- [ ] Version bump latest libs, and access feature availability of the libs we use to provide the LSP interaction.
- [ ] Update currently interaction with LSP, for additional features.
- [ ] Document learnings, and impact on Query Experience.
