### ISSUE TITLE
Spike / Discovery Phase - UI Integration of Invokable Scripts

### ISSUE THREAD

**Issue by asalem1** [influxdata/ui#4918]
### Purpose

The purpose of this issue is to capture the work required in order to complete the discovery phase of the UI portion of the invokable scripts epic.

### TODOs

- [ ] Find out if there's a feature flag for the API?
- [ ] Review the [OpenAPI PR](https://github.com/influxdata/openapi/pull/349/files) and see what is available for the API / what changes have been made
- [ ] If a feature flag exists on the API, should we have a separate one on the UI? - Yes
- [ ] Outline the scope of work required for version 1
- [ ] What designs are available to us for this work to be based off of
- [ ] Check for existing tech debt / ways of improving the code as we go - we fire 2 of the same request on task edits, why?
- [ ] Evaluate the existing tests to see if there are gaps in coverage that we can add towards to ensure stability
