### ISSUE TITLE
EPIC: schema composition

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#5337]
**There may already be an epic. Please link if this is duplicate.**

## Schema Composition:

The initial release of the schema injection, for Q2, was based on a quick hack which does not support the full desired feature set. The goal of this epic is to implement a LSP-monacoEditor-UI skeleton which supports a more full featured product design.

### Features:
* multiple selection:
  * multiple fields being added ("any of" OR expressions)
  * multiple tags being added ("all of" AND expressions)
* definition of a "compostion"
  * reserved block of code
  * under absolute control of the LSP
  * a way to programmatically identify (versus result of flux query)
  *  need out, decide when/how no longer under control of the LSP.
      * e.g. user raw edits in the block
* UX for sync:
  * what it means to be in sync
  * what the UI visual for sync is
  * what triggers removal of sync
  * when can do back (on/off) with sync
  * when irreversibly exit sync
* proper division/consideration of responsibilities:
  * LSP = creation of valid flux (the injection itself)
  * session state = UI stateful src of truth, for schema builder (outside of editor)
  * monaco-editor = src of truth for query string itself (a requirement of that lib)
  * schema browser GUI = user inputs
  * coordination between the LSP vs monaco-editor vs UI

### Brainstorm:
https://docs.google.com/document/d/1W04MvFL0EBvZrJTM01jAH5hMw6VGPlI-bIApA380hlY/edit#heading=h.24dg4bs3w7vc

## Subtasks:
- [x] LSP composition injection
   * https://github.com/influxdata/flux-lsp/issues/549
   - [x] add schema elements
   - [x] remove schema elements
   - [x] wire module into LSP server
   - [ ] **planned Q4?** have function injection into the composition block.
- [x] Design
   - [x] sync interaction
        * https://github.com/influxdata/ui/issues/5338
   - [x] schema browser, and selected badges 
        * https://github.com/influxdata/ui/issues/5339
- [ ] coordination between the LSP vs monaco-editor vs UI:
   - [x] Q3 release. (PoC is ready.)
        * https://github.com/influxdata/ui/issues/5342
   - [x] Middleware.
        * design it: https://github.com/influxdata/ui/issues/5305
        * build it: https://github.com/influxdata/ui/issues/5717
- [x] UI updates
   - [x] **planned Q4.** fields versus tags:
        * https://github.com/influxdata/ui/issues/5446
   - [x] for selected options. UI element and wire to session.
        * https://github.com/influxdata/ui/issues/5471
        * https://github.com/influxdata/ui/issues/5351
   - [x] instructions for the user (what composition is, etc) 
        * https://github.com/influxdata/ui/issues/5340
   - [x] UI events
        * https://github.com/influxdata/ui/issues/5479

**Comment by wiedld** [comment]
After first demo, got feedback on UI design and the basic overall approach. Those are cataloged here:
- [ ] https://github.com/influxdata/ui/issues/5573
- [ ] https://github.com/influxdata/ui/issues/5575

**Comment by wiedld** [comment]
Also adding testing requirements:
- [ ] e2e tests for cypress integration with other UI bits. (session store, Load/Save, page reload, etc)
      * https://github.com/influxdata/ui/issues/5591
- [ ] integration and/or unit tests for the facade integration, middleware, etc
      * this can occur after the "cleanup PoC decisions" issue.

**Comment by wiedld** [comment]
Already done everything we plan to do here. Closing.
