### ISSUE TITLE
Schema Composition: UI design feedback

### ISSUE THREAD

**Issue by appletreeisyellow** [influxdata/ui#5573]
The feedback was originally listed [on Slack](https://influxdata.slack.com/archives/C030G5783M3/p1661539113483789?thread_ts=1661536428.564019&cid=C030G5783M3)

- [x] The highlighting overlay shouldn't be shown outside of the Monaco editor as Hannah mentioned (#5570)
- [x] Update the icon to the new sync icon that's now in clockface (#5569)
- [x] If sync is turned off the icon should be gray, not blue (#5574)
- [x] Small detail, but can we separate the sentences for the feature description on hover? It just makes it a little easier to scan the info ([see mock here](https://www.figma.com/file/0qAntPk5LVangAHguWT74X/Query-Experience-Project?node-id=1719%3A82252)) (#5597)
- [x] When sync is disabled, the feature title "Flux Sync" should also use the disabled styling (50% opacity) (#5585)
- [x] Injecting a flux function looks like it's being added after the composition, but it's still disabling the sync.
    * this is because function injection is separate from schema composition, in the LSP.
    * therefore any function injection irreversibly makes schema composition diverge/end.
    * we have this as a potential Q4 goal. If/how/when to include functions in the composition block.
- [x] If sync is disabled, the icon and highlight shouldn't be shown (#5699)
- [x] Add the instructions to the Monaco editor to let users know how to start (this is a small things, but I think this will make a big impact)
    * this is duplicated in #5340 
- [x] There seems to be some issues with how the sync highlighting shows when starting a new script  after having ran a previous script. Sometimes the sync highlight doesn't show even when the toggle is turned on, but if I refresh the page, then it shows again. Other times the grayed out highlight shows from the previous query, when it shouldn't be shown. (#5719)

**Comment by appletreeisyellow** [comment]
@juliajames12  @wiedld think

I was fixing the last task and found another bug for schema composition icon and highlight. I'd like to hear what do you think

# The bug

https://user-images.githubusercontent.com/14298407/189435330-60e9f98c-038e-400b-a9fe-53f88b79b3c8.mov

I found a way to use the Monaco editor API to fix the bug for highlight, but I have some challenges with the icon. As you see from the video below, the icon sticks at the upper-left of the editor and it doesn't move when user scrolls the editor.

# Current fix 

https://user-images.githubusercontent.com/14298407/189435459-0337cb2d-b7eb-4db1-ad58-11b865e63669.mov

I'd like to get some idea on what we want to do with the icon. Here are two options I can think of:

1) Keep the icon as shown in the above video, i.e. icon stick on the upper-left. And this icon is clickable to turn the sync on/off. (The code is in this draft PR #5719)

2) Make the icon to be part of the highlight, i.e. when user scrolls the editor, the icon moves with he highlight as a whole entity. However, this icon is not clickable since Monaco editor doesn't have such API

I prefer option 2 since there is already a sync toggle in the schema browser for turning the sync on/off, and it's very close to the icon, so it's not necessary to have the icon to be clickable as well. In addition, it makes more sense to see the icon move with highlight as an entity.

**Comment by juliajames12** [comment]
@appletreeisyellow Yeah I prefer option 2 as well. Since we already have the toggle, we no longer need to be able to turn on and off from the icon. Thanks for working on this!

**Comment by wiedld** [comment]
@appletreeisyellow agreed. Option 2.

**Comment by wiedld** [comment]
Done. Closing.
