### ISSUE TITLE
SQL authoring support: Phase I

### ISSUE THREAD

**Issue by rockstar** [influxdata/ui#6047]
In Phase I of the SQL authoring/editing, we'll introduce some rudimentary sql authoring tools (see #5958 for more details). This will require the following work to be done:

- [x] Schema browser read-only (no checkboxes) when sql file is loaded in the editor.
- [x] UI to open file as sql
- [x] UI to indicate file type (the user needs to know whether they're expected to write SQL or Flux before they start seeing squiggly red lines)
- [x] SQL file can be saved and loaded again
- [x] Monaco editor component understands model to be sql, i.e. it doesn't try and send the file to the flux lsp. Right now, the component hard codes flux, and doesn't have availability for other document types. Models should keep track of their own file type, using [the optional `language` parameter in `createModel`](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#createModel).
- [x] `runQuery` support for running the sql query by submitting the sql query as flux, using `iox.sql(bucket: params.bucket, query: params.query)`

**Comment by garylfowler** [comment]
@rockstar - Should we add removal/collapse of flux function panel and removal of the flux sync indicator to this ticket, or would you like me to create separate tickets for those and consider them outside the scope of this ticket?

**Comment by hralexander** [comment]
Schema Browser Read Only mode
https://github.com/influxdata/ui/issues/6103

UI Changes
https://github.com/influxdata/ui/issues/6104

Save/Load
https://github.com/influxdata/ui/issues/6105

Monaco Editor
https://github.com/influxdata/ui/issues/6106

Run Query Support
https://github.com/influxdata/ui/issues/6107

**Comment by wiedld** [comment]
Tasks are all complete. Closing ticket.
