### ISSUE TITLE
EPIC: Flux composition, integration of yieldless

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#6334]
After the `|> yield(name: "_editor_composition")` was removed as part of [this work](https://github.com/influxdata/flux-lsp/issues/583), we need to handle integration with the UI. This includes, but is not limited to, the follow use cases:
* getting the basic composition working
* With removal of the yield...how can we visually indicate to the user, where is the current composition block being edited?
* how handle flux "sync" and "divergence"?
     * is the concept of "divergence detected by the UI" still hold?
* how often does the LSP fail to update the composition block?
     *  if frequent, how handle these errors? 

## Implementation:
This is the current implementation, in progress:
- [x] FIRST TASK: determine if the executeCommands sent the LSP, results in the predicted output code in the UI.
     * https://github.com/influxdata/flux-lsp/issues/615
     * https://github.com/influxdata/ui/issues/6341
- [x] SECOND TASK: which server-side events (LSP spec) to use? how get UI listening and reacting to these events?
     * confirmed. Found a way. PoC is [this commit here](https://github.com/influxdata/ui/commit/c6597932850b39cf3244d0fae9453ec988763e52), with a detailed commit message on all approaches tried.
     * Server-initiated showMessage ActionItems, intercepted in the UI:
         *  ![Screen Shot 2022-12-01 at 6 30 12 PM](https://user-images.githubusercontent.com/10232835/205201448-b7eb0e6a-133c-4582-93f3-e9a4e33ee0f8.png)

- [x] THIRD TASK: using the LSP triggered events, do the following:
     * provide UX to indicate location of the composition code block
     * give UX to state when composition is dropped.
          * can we still re-init a new composition, after the last is dropped? 
     * how often does the LSP fail to update the composition block?
          *  if frequent, how handle these errors?

**Comment by wiedld** [comment]
FIRST TASK: outcome.
* edits basic block
* preserves user changes to the `|> range()` and transformations added after the block.
* when selecting new measurement --> is the same block.
* when selecting new bucket --> inits a new composition.

https://user-images.githubusercontent.com/10232835/203623726-24a17c23-7600-436b-bccd-8e8e1c72e1f9.mov


Only thing not resolved; is part of THIRD TASK:
* sometimes there is ambiguity with the current composition block, and another subquery (a.k.a. a previous composition).
  * when this occurs, the composition is dropped in the server.
  * once that occurs --> the LSP server stops responding.
  * use case: usually (not always) when the same bucket+measurement is occurring twice.

**Comment by wiedld** [comment]
Merged.
