### ISSUE TITLE
EPIC: implement SQL data viz for QxBuilder

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#6482]
Reasoning behind this EPIC is [documented in this spike](https://github.com/influxdata/ui/issues/6085#issuecomment-1380974158).

In brief, we are splitting by the table query vs the graph query. Then we apply "magic" to make the graphs work. 

## Tasks
Each checkbox (tasks) can be done independently. a.k.a. is a minimum merge-able unit, without a feature flag.
- [x] make the query for the table, be different than the query for the graph.
   - https://github.com/influxdata/ui/issues/6483
- [x] if data is truncated for graph query --> display message in graph view
- [x] when choosing graph --> auto-open the Customize options in right hand panel.
   * for SQL and flux
- [x] for graph view, add option for data smoothing:
   * for SQL
   * view:
       * Dropdown: nothing, fieldA, fieldB, fieldC
       * ? description of what it does
   * state:
      * persist graph options
      * dataSmoothing: null | fieldName
- [x] Handling tagKeys:
   - https://github.com/influxdata/ui/issues/6496
   - checkboxes. (any_of)
   - by default, append `|> group([<all-tagKeys>])` to each iox.sql() query
       * add button to "show ad hoc query sent"
   - Add grouping checkboxes in Customize graph options:
       * toggle on/off which tags to include in the groupings
- [x] Handling fields:
   -  radio button. (one_of)
   -  By default set a field to view
   -  field --> `valColumn` in `polyline.rdp()`
   -  onFieldSelect() → place in persistence context
- Handling axis defaults:
   - [x] ~X axis default: `_time` or `time`~ Already done. 
   - [x] Y axis default (order to preference).
- [x] affordance → see "my query sent for the graph"
- [x] fix discovered bug:
   -  https://github.com/influxdata/ui/issues/6503
- [ ] All the tests!

## Example with polyline (data smoothing):
Outcome produces same `_time` and `_value`.
Most of the graphs just work. (Or at least, "work" to the same level as it does in flux.)

https://user-images.githubusercontent.com/10232835/212179155-b2abaa02-3ef9-4f6b-a343-f030ed730e87.mov

## Example without polyline:
Need to choose the default option (e.g. Y column). We will be programmatically choosing the initial default.
Fewer of the graphs will work, without the user doing additionally efforts on their own -- such as modifying the graph options and/or the query.
(Note: the default is polyline being on.)

https://user-images.githubusercontent.com/10232835/212179941-680dde80-56ae-4c3f-b87d-d931721056d8.mov
