### ISSUE TITLE
InfluxQL Support in Script Editor

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#6491]
### EPIC Description

This EPIC is for the addition of a 3rd script type in the New Script Editor: InfluxQL.

**Background:**  The new IOx storage engine includes support for InfluxQL.   There are a number of Cloud 1 customers that are heavily invested in InfluxQL and it has been a barrier of adoption of Cloud 2 since it does not currently have InfluxQL support.  Adding InfluxQL to the script editor will reduce the reluctance of customers to move off of Cloud 1 and onto our IOx enabled platform.

### General Requirements & AC:

- When clicking on "New Script" inside the script editor, the user will be shown a 3rd option (in addition to the current SQL and Flux Options): InfluxQL
- When InfluxQL is selected the user we will be given a blank script editor, with a schema browser on the left and a display panel below - just like the Flux and SQL editors
- The user can type InfluxQL queries into the editor; upon hitting run the InfluxQL query will be executed
- When the Query Completes, the user will be shown a result table - like with Flux and SQL editing.  There is no need for a "graph" option.
- If there is an error with the query, the user will be shown the error

### Other Requirement Considerations

**InfluxQL LSP Support** - It is not required to integrate an InfluxQL LSP; the editing window can simple be a text edit block.  But if we do have something we could take from Cloud 1 that could easily be integrated, it is desirable - but again, not required.

**Schema Browser** - Like with the flux and SQL editor, the user should have a schema view.  The generation of the schema view itself does not have to come via InfluxQL queries; this can utilize SQL or Flux and doesn't have to be changed from its currently functionality to be used with InfluxQL.

**InfluxQL Injection** - It is desirable to be able to inject InfluxQL statements based on Schema Selections to be consistent with functionality from the other two languages; however, this is only a nice to have and is not a hard requirement.  Its importance is less than it was for SQL as that would encourage SQL use versus flux.  In this scenario, the user has SQL as an option already, so having this capability in InfluxQL is not quite as important.  

**Schema Sync** - While desirable to have this feature, it is definitely not a requirement.  It's importance is less than it was with the SQL editing function.

**Function Injection** - Function Injection is not required for InfluxQL editing; the function window can be hidden, like it is with the SQL editor.

**Result Window** -  Existing Result Window should be used if the table view works ok with the format of the data returned with InfluxQL.  The "search" capability is a nice-to-have if it can be retained.

**Date/Time Picker**- If InfluxQL Injection is not added, then there is no reason to have a date/time picker as the user will be manually entering their searches.  If Injection is included, then it would be desirable to have the date/time picker included.

**Load/Save** - Load/Save should utilize the scripts API and work just like SQL and Flux - just with a different  script"type" saved.

**Visualization/Graphs** - There is no requirement for Visualizations unless they somehow come for free - meaning the data comes back in the exact same format as flux and so the existing visualizations work automatically with them.  Otherwise, the Table/Graph button can be removed and only the table result needs to be displayed.

```[tasklist]
# Tasks
- [x] https://github.com/influxdata/ui/issues/6564
- [x] https://github.com/influxdata/ui/issues/6565
- [x] https://github.com/influxdata/idpe/issues/17070
- [x] https://github.com/influxdata/ui/issues/6629
- [x] https://github.com/influxdata/idpe/issues/17205
- [x] https://github.com/influxdata/ui/issues/6638
- [x] https://github.com/influxdata/ui/issues/6631
- [x] https://github.com/influxdata/ui/issues/6637
- [x] https://github.com/influxdata/ui/issues/6652
- [x] https://github.com/influxdata/idpe/issues/17075
- [x] https://github.com/influxdata/idpe/issues/17173
- [x] https://github.com/influxdata/ui/issues/6630
- [x] https://github.com/influxdata/ui/issues/6653
- [x] https://github.com/influxdata/idpe/issues/17668
- [x] https://github.com/influxdata/ui/issues/6632
- [x] https://github.com/influxdata/idpe/issues/17672
- [x] https://github.com/influxdata/idpe/issues/17689
- [x] https://github.com/influxdata/ui/issues/6730
- [x] https://github.com/influxdata/ui/issues/6704
- [x] https://github.com/influxdata/ui/issues/6633
- [ ] https://github.com/influxdata/ui/issues/6703
- [ ] https://github.com/influxdata/ui/issues/6726
- [ ] https://github.com/influxdata/idpe/issues/17803
```

```[tasklist]
# Bugs
- [ ] https://github.com/influxdata/ui/issues/6714
- [ ] https://github.com/influxdata/ui/issues/6715
- [ ] https://github.com/influxdata/ui/issues/6724
```

Some additional works that has less priority are tracked in https://github.com/influxdata/ui/issues/6738

**Comment by gavincabbage** [comment]
Thinking we do this in two phases:
1. Basic functionality/requirements: Text box, new script language type can be created and saved, execute a query against `/query`, show result table or error
2. Stretch goals. Injection, LSP, sync, viz, etc.

**Comment by wiedld** [comment]
## Unknowns:
- [ ] spike to determine best method to query backend


## Knowns:
- [ ] create new `LanguageType`, and apply to all script interfaces. 
  * do not yet add as option to dropdown script languages, until we are ready for release. Or feature flag it's inclusion in this list.
  * easy search yields [this](https://github.com/influxdata/ui/search?p=1&q=LanguageType), but typescript will also be a good aid.

- [ ] language features in the editor
   - [ ] make a new InfluxQL editor component
         * see example [SQL editor](https://github.com/influxdata/ui/blob/master/src/shared/components/SqlMonacoEditor.tsx)
   - [ ] add hotkeys support
         * [see SQL version](https://github.com/influxdata/ui/blob/master/src/languageSupport/languages/sql/monaco.sql.hotkeys.ts), and wire into editor component
   - [ ] syntax theme
         * in SQL, we use the monaco-editor SQL tokenizer which is [wired in here](https://github.com/influxdata/ui/blob/master/src/languageSupport/languages/sql/monaco.sql.syntax.ts). That will not work with InfluxQL. Instead, we can implement our own, but that's very straighforward and we already have an example (via monaco-editor's one) [here](https://github.com/microsoft/monaco-editor/tree/main/src/basic-languages/pgsql).
         * Then, we simply determine the theme to add per each token. Here is [the SQL-example](https://github.com/influxdata/ui/blob/master/src/languageSupport/languages/sql/monaco.sql.theme.ts) in our code.
   - [ ] composition 
         * already have an example of [the SQL-specific connector implementing composition](https://github.com/influxdata/ui/blob/master/src/languageSupport/languages/sql/connection.ts).

- [ ] integrate query path for influxQL?
         * unclear of this scope, until after the spike

**Comment by wiedld** [comment]
Link to feature: https://influxdata.productboard.com/feature-board/planning/features/17438550

**Comment by gavincabbage** [comment]
Question from grooming session:
- Expose bucket concept in InfluxQL (in addition to DBRPs)? [Gavin]
- Can InfluxQL return annotated CSV? [Denise]
-

**Comment by appletreeisyellow** [comment]
@garylfowler Are we going to support CSV download for InfluxQL like we did for Flux and SQL?

<img width="1196" alt="Screen Shot 2023-05-26 at 1 56 05 PM" src="https://github.com/influxdata/ui/assets/14298407/cc23dc9e-35dd-4ee9-8c11-1999b0676620">

My understanding is yes, but just want to double check with you. If we are going to add CSV download support, then there are extra work on the backend needs to do in order to support large size CSV download.

**Comment by garylfowler** [comment]
Desirable, but can wait for future prioritization; you can leave this out for now.

**Comment by appletreeisyellow** [comment]
@garylfowler All the MVP works tracked in this issue are done. Other additional works with less priority are tracked in https://github.com/influxdata/ui/issues/6738
